### ISSUE TITLE
Issue in installing Kylin node in mac

### ISSUE THREAD

**Issue by sbnair** [Kylin-Network/kylin-node#8]
I am getting following issues while installing , this is my tool chain information in mac :

installed toolchains
--------------------

stable-x86_64-apple-darwin (default)
nightly-2020-10-06-x86_64-apple-darwin
nightly-x86_64-apple-darwin

Error shown below :

 Rust WASM toolchain not installed, please install it!

  Further error information:
  ------------------------------------------------------------
     Compiling wasm-test v1.0.0 (/tmp/.tmp65XFka)
  error[E0463]: can't find crate for `std`
    |
    = note: the `wasm32-unknown-unknown` target may not be installed

  error: aborting due to previous error

  For more information about this error, try `rustc --explain E0463`.
  error: could not compile `wasm-test`

  To learn more, run the command again with --verbose

**Comment by matt-paul** [comment]
@sbnair Have you tried running `rustup target add wasm32-unknown-unknown`?

**Comment by sbnair** [comment]
Yes, I have tried that, still the same issue.
________________________________

**Comment by samelamin** [comment]
I will be pushing a fix for this in the docker file over the next few days, you should be able to look at the docker instructions and replicate for Mac. I personally got it working on my Mac

**Comment by samelamin** [comment]
Docker file is now fixed
