### ISSUE TITLE
Failure to transferring funds to a test account.

### ISSUE THREAD

**Issue by jiangjkd** [Kylin-Network/kylin-node#9]
1002: Verification Error: Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature: RuntimeApi, Execution: Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature

**Comment by samelamin** [comment]
Hi  @jiangjkd  sorry for the late reply, I only just joined the team full time. 
The reason for the error is that you still need credentials to access the API. I will be publishing a guide soon to help you get your local node running. In the meantime I will keep this ticket open so others can understand the cause

**Comment by samelamin** [comment]
The API has been removed so this issue can now be closed
